# Generated by Django 4.2.11 on 2024-05-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240501_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='nombre',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='precio',
            new_name='titulo',
        ),
    ]
