# Generated by Django 4.2.11 on 2024-04-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
