# Generated by Django 4.2.11 on 2024-04-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_contenido'),
    ]

    operations = [
    ]
