# Generated by Django 4.2.11 on 2024-04-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240423_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contenido',
        ),
    ]
