# Generated by Django 4.2.11 on 2024-04-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='update',
            new_name='updated',
        ),
    ]
