# Generated by Django 4.2.11 on 2024-05-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_categoria_remove_blog_categorias_remove_blog_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
