# Generated by Django 4.2.11 on 2024-05-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
